---
title: "Olympic Data Study"
author: "Dan Burke, Rajinder Singh, Marley Akonnor"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown
```{r cars}
#Created a function to Check for NA values
checkForNaValuesInColumn <- function(vec, colname){
  numberOfNas <-length(vec[is.na(vec)])
  print(colname)
  print(numberOfNas)
}

#read the CSV, Create a Data Frame from each Dataset
athleteEvents <- data.frame(read.csv("C:\\Users\\danbu\\Desktop\\OlympicData\\athlete_events.csv"))
nocRegions <- data.frame(read.csv("C:\\Users\\danbu\\Desktop\\OlympicData\\noc_regions.csv"))

#Grab the column names for reference
athleteColumnNames <- colnames(athleteEvents) 
regionColnames <- colnames(nocRegions)

#Replace NA values for Medals with "None", we can assume a NA == no medal, however we can't assume the same for any other values
athleteEvents$Medal[is.na(athleteEvents$Medal)] <- "None"

#check For NA values
checkForNaValuesInColumn(athleteEvents$Name, "Name")
checkForNaValuesInColumn(athleteEvents$Sex, "Sex")
checkForNaValuesInColumn(athleteEvents$Age, "Age")
checkForNaValuesInColumn(athleteEvents$Height, "Height")
checkForNaValuesInColumn(athleteEvents$Weight, "Weight")
checkForNaValuesInColumn(athleteEvents$Team, "Team")
checkForNaValuesInColumn(athleteEvents$NOC, "NOC")
checkForNaValuesInColumn(athleteEvents$Games, "Games")
checkForNaValuesInColumn(athleteEvents$Year, "Year")
checkForNaValuesInColumn(athleteEvents$Season, "Season")
checkForNaValuesInColumn(athleteEvents$Sport, "Sport")
checkForNaValuesInColumn(athleteEvents$City, "City")
checkForNaValuesInColumn(athleteEvents$Event, "Event")
checkForNaValuesInColumn(athleteEvents$Medal, "Medal")




#Omit all NA rows within the Athlete Events Data Frame

athletes1 <- na.omit(athleteEvents)



print("Number of Omitted Rows")
print(length(athleteEvents$ID)-length(athletes1$ID))

#Reivew the Data Frame
str(athletes1)


#Convert CM to Feet (Decimal)
athletes1$Height <- athletes1$Height / 30.48

#Convert KG to lbs

athletes1$Weight <- athletes1$Weight * 2.2

#View Distribution
hist(athletes1$Height)
plot(athletes1$Height)
hist(athletes1$Weight)
plot(athletes1$Weight)
summary(athletes1$Height)
summary(athletes1$Weight)




countries <- read.csv("C:\\Users\\danbu\\Desktop\\OlympicData\\allCountries.csv")

#Clean up Country Name Strings
library(stringr)

#Match up Countries & Athletes we have locations for, with the change in country names this will affect the data
matchedCoAthIndex<- athletes1[match(athletes1$Team, countries$name),]
matchedCoAthIndex <- na.omit(matchedCoAthIndex)

#Get the Athletes who have never medal'd,We know that countries can medal and not medal one year so we 
#must find countries which have not recieved a medal at all
countries <- unique(athletes1$Team)
countries <- lapply(countries, sub, pattern = '\\-1', replacement = '')
countries <- lapply(countries, sub, pattern = '\\-2', replacement = '')
countries <- lapply(countries, sub, pattern = '\\-3', replacement = '')
countryMedalSum <- data.frame()

for(i in 1:length(countries)){
  countryMedalSum[i,1] <- countries[i]
  countryMedalSum[i,2] <- nrow(athletes1[which(athletes1$Team == countries[i] & athletes1$Medal =="Gold"),])
  countryMedalSum[i,3] <- nrow(athletes1[which(athletes1$Team == countries[i] & athletes1$Medal =="Silver"),])
  countryMedalSum[i,4] <- nrow(athletes1[which(athletes1$Team == countries[i] & athletes1$Medal =="Bronze"),])
  countryMedalSum[i,5] <- nrow(athletes1[which(athletes1$Team == countries[i] & athletes1$Medal =="None"),])
  #Get and Add the sum for each medal
  countryMedalSum[i,6] <- sum(
    nrow(athletes1[which(athletes1$Team == countries[i] & athletes1$Medal =="Gold"),]),
    nrow(athletes1[which(athletes1$Team == countries[i] & athletes1$Medal =="Silver"),]),
    nrow(athletes1[which(athletes1$Team == countries[i] & athletes1$Medal =="Bronze"),]),
    nrow(athletes1[which(athletes1$Team == countries[i] & athletes1$Medal =="None"),])
  )
}



colnames(countryMedalSum) <- c("team", "Gold", "Silver", "Bronze", "None", "Total Athletes") 

countryGeo <- read.csv("C:\\Users\\danbu\\Desktop\\OlympicData\\allCountries.csv")
countryMedalSum <- countryMedalSum[match(countryGeo$name,countryMedalSum$team),]
countryMedalSum <-na.omit(countryMedalSum)

for(i in 1:length(countryMedalSum$team)){
  countryMedalSum$lats[i] <- countryGeo[which(countryGeo$name == countryMedalSum[i,1]), 2]
  countryMedalSum$longs[i] <- countryGeo[which(countryGeo$name == countryMedalSum[i,1]), 3]
}

colnames(countryMedalSum) <- c("team", "Gold", "Silver", "Bronze", "None", "Total Athletes", "lat", "long") 

#Write it to a csv in order to keep the siny app more simple

path_out = "C:\\Users\\danbu\\Documents\\GitHub\\IST687\\Dan\\Data Cleaning Etc\\"
fileName = paste(path_out, 'medalSums.csv',sep = '')
write.csv(countryMedalSum,fileName)



library(shiny)
library(leaflet)
library(shinydashboard)
library(scales)
library(leaflet.minicharts)

#install.packages("leaflet.minicharts")
#https://rstudio.github.io/leaflet/markers.html#circle-markers
countryMedals <- read.csv("C:\\Users\\danbu\\Documents\\GitHub\\IST687\\Dan\\OlympicGamesMap\\OlyMap\\medalSums.csv")



colors <- c("#FFFF33", "#CECCB7", "#EE9A25")
MiniBarDf <- data.frame(countryMedals$Gold, countryMedals$Silver, countryMedals$Bronze)
colnames(MiniBarDf) <- c("Gold", "Silver", "Bronze")
MiniBarDf <- MiniBarDf
scaledTotalAthletes <- rescale(countryMedals$Total.Athletes, to = c(100000,750000))



ui <- dashboardPage(
    dashboardHeader(title = "IST 687 - Olympics"),
    dashboardSidebar(
        sidebarMenu(
            menuItem(
                "Maps", 
                tabName = "maps", 
                icon = icon("globe"),
                menuSubItem("Countries", tabName = "m_country", icon = icon("map")),
                menuSubItem("Total Athletes", tabName = "m_tot_ath", icon = icon("map"))
            ),
            menuItem(
                "Charts", 
                tabName = "charts", 
                icon = icon("bar-chart"),
                menuSubItem("Countries", tabName = "c_Countries", icon = icon("area-chart")),
                menuSubItem("Total Athletes", tabName = "c_Total_Athletes", icon = icon("area-chart"))
            )
        )
    ),
    dashboardBody(
        tags$style(type = "text/css", "#map {height: calc(100vh - 80px) !important;}"),
        leafletOutput("map")
    )
)

server <- function(input, output, session) {
    
    output$map <- renderLeaflet({
        leaflet() %>%
            addTiles(group="OSM")%>%
            setView(lat = 40.459152,
                    lng =  49.426570,
                    zoom = 4
            ) %>% 
            addCircles(lng=countryMedals$long, 
                       lat=countryMedals$lat,
                       radius=scaledTotalAthletes, 
                       popup=paste(countryMedals$team,"Total Athletes", as.character(countryMedals$Total.Athletes, " ")),
                       color = "#3462eb",
                       fillOpacity = 0.15,
                       stroke=FALSE
            )%>%
            addMinicharts(countryMedals$long,
                          countryMedals$lat,
                          type = "pie", 
                          chartdata = MiniBarDf, 
                          colorPalette = colors, 
                          legend = TRUE, 
                          legendPosition = "topright",
                          width = 20, height = 20)
                        
    })
}







```




